openapi: 3.0.1
info:
  title: '@jupiterone/graph-hashicorp-vault'
  description: A JupiterOne Integration for ingesting data of Hashicorp Vault
  x-cortex-git:
    github:
      repository: JupiterOne/graph-hashicorp-vault
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-hashicorp-vault'
